FROM node:23-alpine AS builder
WORKDIR /app
COPY package*.json .
RUN npm install
COPY . .
RUN npm run build


FROM nginx:1.27-alpine AS prod 
WORKDIR /app
COPY --from=builder /app/build /usr/share/nginx/html
COPY --from=builder /app/package*.json ./
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
