apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secrets
type: Opaque
data:
  username: {{ .Values.database.username | b64enc }}
  password: {{ .Values.database.password | b64enc }}



---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
data:
  JWT_SECRET: c29tZXRoaW5nc2VjcmV0
  MONGODB_URI: bW9uZ29kYjovL3Jvb3Q6ZXhhbXBsZUBkYXRhYmFzZToyNzAxNw== 
  CLOUDINARY_API_SECRET: "" # Leave empty if unset
  CLOUDINARY_URL: ""        # Leave empty if unset
  PAYPAL_CLIENT_ID: ""      # Leave empty if unset
  CLOUDINARY_API_KEY: ""    # Leave empty if unset
  CLOUDINARY_CLOUD_NAME: "" # Leave empty if unset
  GOOGLE_API_KEY: ""        # Leave empty if unset
  MAILGUN_DOMIAN: ""        # Leave empty if unset
  MAILGUN_API_KEY: ""       # Leave empty if unset
