apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}-mongo
spec:
  serviceName: "mongo"
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-mongo
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-mongo
    spec:
      containers:
      - name: mongo
        image: mongo
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-storage
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongo-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
